# Generated by Django 5.2.11 on 2026-05-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('age', models.IntegerField(verbose_name='العمر')),
                ('email', models.EmailField(max_length=254, verbose_name='الإيميل')),
                ('phone', models.CharField(max_length=20, verbose_name='الرقم')),
            ],
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
