# Generated by Django 5.2.11 on 2026-05-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_driver_delete_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
